### ISSUE TITLE
Experiencing slow performance after latest update

### ISSUE THREAD

**Issue by sumitd1301** [rajyraman/mscrmexporttoexcel#29] opened 2021-11-29 14:50 UTC
@rajyraman  This is a really helpful tool to export huge data of Dynamics 365 entity. However, the processing of the data fetch of the tool is rigorously slow after the latest update, and also, after a long run, it gives the connection a lost error. please look into it and make it work like before. Thanks!

**Comment by beginner-luck1** [comment] 2021-11-30 15:52
I have to admit, I relied a lot on this tool beforehand (without realising exactly how much) until the recent update which appears to have killed the exporting performance. Please look at fixing this tool, it was wonderful.

Thanks,

**Comment by rajyraman** [comment] 2021-11-30 17:05
@sumitd1301 - I already rolledback most changes. The only one left to rollback is EPPlus to the older version. Would you be able to verify this, if I build a new version with older version of EPPlus?

**Comment by beginner-luck1** [comment] 2021-11-30 17:43
I'll be honest, if a "new" version is available to install via the "Tool Library" I will give it a shot for you. Unfortunately I am not in IT, so I can't "hack" install anything. My work laptop is locked down, and I am not a developer.

**Comment by rajyraman** [comment] 2021-11-30 21:33
@beginner-luck1 - Tracked down the issue to a PR that I merged. The issue is caused due to Optionset value not cached. Fixed the issue in 3.0.3.

**Closed as completed by rajyraman** 2021-11-30 21:33 UTC

**Comment by beginner-luck1** [comment] 2021-11-30 22:04
Brilliant job, thank you, working as it used to. Thanks so much for this, it is greatly appreciated.

**Comment by sumitd1301** [comment] 2021-12-01 11:50
@rajyraman Thank you so much to fixed it, appreciate your promptness. It's working as expected and as before.
@beginner-luck1 Thanks a  lot to verify quickly. much appreciated.
